# Generated by Django 3.2.6 on 2022-04-13 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('S_Record', '0002_schoolalbumimages_schoolalbumvideos_schoolannouncements_schooldetail_schoolfeestructure'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
