# Generated by Django 3.2.6 on 2022-04-06 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('S_Teachers', '0001_initial'),
        ('S_Record', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('clas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='S_Record.classsection')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='S_Record.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='S_Teachers.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='HomeworkVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.URLField()),
                ('text', models.CharField(blank=True, max_length=300, null=True)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='S_Homework.homework')),
            ],
        ),
        migrations.CreateModel(
            name='HomeworkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='Homework/Images/')),
                ('text', models.CharField(blank=True, max_length=300, null=True)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='S_Homework.homework')),
            ],
        ),
    ]
