# Generated by Django 3.2.6 on 2022-04-13 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('S_Students', '0004_alter_studentfee_fee_type'),
        ('S_Fee', '0002_delete_feetypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFeeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=9)),
                ('due_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Due', 'Due')], max_length=5)),
                ('paid_date', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='S_Students.studentfee')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='S_Students.student')),
            ],
        ),
    ]
