# Generated by Django 3.2.6 on 2022-04-13 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('S_Fee', '0003_studentfeerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfeerecord',
            name='paid_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
