# Generated by Django 3.2.6 on 2022-04-13 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('S_Fee', '0004_alter_studentfeerecord_paid_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfeerecord',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=9),
        ),
    ]
