# Generated by Django 3.2.6 on 2022-04-13 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('S_Fee', '0005_alter_studentfeerecord_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfeerecord',
            name='due_date',
            field=models.DateField(),
        ),
    ]
