# Generated by Django 3.2.6 on 2022-04-19 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('S_Fee', '0006_alter_studentfeerecord_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfeerecord',
            name='year',
            field=models.IntegerField(default=2022),
            preserve_default=False,
        ),
    ]
