# Generated by Django 3.2.6 on 2022-06-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('S_Fee', '0007_studentfeerecord_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfeerecord',
            name='paid_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentfeerecord',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Due', 'Due'), ('PartialyPaid', 'PartialyPaid')], max_length=15),
        ),
    ]
