# Generated by Django 3.2.6 on 2022-04-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('S_Fee', '0008_studentfeerecord_paid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfeerecord',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Due', 'Due'), ('PartialyPaid', 'PartialyPaid')], max_length=15),
        ),
    ]
