# Generated by Django 3.2.6 on 2022-04-06 02:57

from django.db import migrations, models
import django.db.models.deletion
import django_tenants.postgresql_backend.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('short_name', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=250)),
                ('full_name', models.CharField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('principal_name', models.CharField(max_length=50)),
                ('easypaisa', models.BigIntegerField(blank=True, null=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to='School/Logo/')),
                ('active', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='S_School.school')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
