# Generated by Django 3.2.6 on 2022-04-13 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('S_Record', '0003_feetypes'),
        ('S_Students', '0003_studentfee_fee_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfee',
            name='fee_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='S_Record.feetypes'),
        ),
    ]
