# Generated by Django 3.2.6 on 2022-06-19 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('T_Attendance', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherAttendance',
        ),
    ]
