# Generated by Django 3.2.6 on 2022-06-19 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('S_Teachers', '0003_auto_20220407_0300'),
        ('T_Attendance', '0002_delete_teacherattendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_attendance', models.DateField()),
                ('capture_datetime', models.DateTimeField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='S_Teachers.teacher')),
            ],
        ),
    ]
