# Generated by Django 3.2.6 on 2022-04-06 02:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('S_School', '0001_initial'),
        ('S_Record', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=500)),
                ('picture', models.FileField(blank=True, null=True, upload_to='Teacher/Pictures/')),
                ('mobile1', models.BigIntegerField()),
                ('mobile2', models.BigIntegerField(blank=True, null=True)),
                ('nic', models.BigIntegerField(blank=True, null=True)),
                ('date_of_interview', models.DateField()),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('religion', models.CharField(choices=[('Islam', 'Islam'), ('Christianity', 'Christianity'), ('Other', 'Other')], max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField()),
                ('left_date', models.DateField(blank=True, null=True)),
                ('reason_of_left', models.CharField(blank=True, max_length=500, null=True)),
                ('remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('last_school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='S_School.school')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('subjects', models.ManyToManyField(to='S_Record.Subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='S_Teachers.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField()),
                ('valid', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='S_Teachers.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('clas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='S_Record.class')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='S_Teachers.teacher')),
            ],
        ),
    ]
