# Generated by Django 3.2.6 on 2022-04-07 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('S_Teachers', '0002_teacheralbumimages_teacheralbumvideos_teacherdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacheralbumimages',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='S_Teachers.teacher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacheralbumvideos',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='S_Teachers.teacher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherdetail',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='S_Teachers.teacher'),
            preserve_default=False,
        ),
    ]
